# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 843ef45a0c93a76cb5be2282356122895ce270a285fb60f69588b6a5f50e65b93eb82b8a7fc2d8f1d0b51ffe1e238b66dcca02204b5c0a44be1f483dd5b76f8d

test:
  secret_key_base: ca830ecfe0b7e65273d0c4a856e14f398329a3b8606e87846bd0c6e83a6acea06e838305f5d6a2d422a8b28c4db2a3ad066fceac3d599b4b65db19e18cb866f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
